apiVersion: v1
kind: ConfigMap
metadata:
  name: global-pull-secret-append-config
data:
  global-pull-secret-append.sh: |
    #!/bin/bash

    export WORK_ROOT=$(pwd)

    oc extract secret/pull-secret \
      -n openshift-config

    echo "global_pull_secret:"
    cat ${WORK_ROOT}/.dockerconfigjson

    echo "DOCKER_SERVER: $DOCKER_SERVER"
    echo "DOCKER_USERNAME: $DOCKER_USERNAME"
    echo "DOCKER_PASSWORD: $DOCKER_PASSWORD"

    oc registry login \
      --registry="${DOCKER_SERVER}" \
      --auth-basic="${DOCKER_USERNAME}:${DOCKER_PASSWORD}" \
      --to=${WORK_ROOT}/.dockerconfigjson

    oc set data secret/pull-secret \
      -n openshift-config \
      --from-file=.dockerconfigjson=${WORK_ROOT}/.dockerconfigjson

