
apiVersion: v1
kind: ServiceAccount
metadata:
  name: global-pull-secret-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: global-pull-secret-sa-role
  namespace: openshift-config
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "dave" to read secrets in the "development" namespace.
# You need to already have a  ClusterRole named "secret-reader".
kind: ClusterRoleBinding
metadata:
  name: global-pull-secret-binding
subjects:
  - kind: ServiceAccount
    name: global-pull-secret-sa1
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: global-pull-secret-sa2
    namespace: openshift-config
roleRef:
  kind: ClusterRole
  name: global-pull-secret-sa-role
  apiGroup: rbac.authorization.k8s.io