
apiVersion: v1
kind: ServiceAccount
metadata:
  name: global-pull-secret-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: global-pull-secret-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["pull-secret"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: global-pull-secret-rb
  #namespace: openshift-config
subjects:
  - kind: ServiceAccount
    name: global-pull-secret-sa
    namespace: openshift-config
  - kind: ServiceAccount
    name: global-pull-secret-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: global-pull-secret-role
  apiGroup: rbac.authorization.k8s.io
