
apiVersion: v1
kind: ServiceAccount
metadata:
  name: global-pull-secret-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: global-pull-secret-role
  namespace: openshift-config
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: global-pull-secret-rb
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: global-pull-secret-sa
    namespace: openshift-config
roleRef:
  kind: Role
  name: global-pull-secret-role
  apiGroup: rbac.authorization.k8s.io
